version: '3.3'
services:
  post_db:
    container_name: mongo_db
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - comment_db
          - post_db
  ui:
    container_name: ui
    image: ${USERNAME}/ui:${UI_SERVICE_VERSION}
    ports:
      - ${SRV_PORT}:9292/tcp
    networks:
      - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
  post:
    container_name: post
    image: ${USERNAME}/post:${POST_SERVICE_VERSION}
    networks:
      - back_net
      - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
  comment:
    container_name: comment
    image: ${USERNAME}/comment:${COMMENT_SERVICE_VERSION}
    networks:
      - back_net
      - front_net
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

volumes:
  post_db:

networks:
  back_net:
    ipam:
      driver: default
      config:
      - subnet: 10.0.2.0/24
  front_net:
    ipam:
      driver: default
      config:
      - subnet: 10.0.1.0/24

