version: '3.3'
services:
  post_db:
    container_name: mongo_db
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - comment_db
          - post_db
  ui:
    container_name: ui
    image: ${USERNAME}/ui:${UI_SERVICE_VERSION}
    ports:
      - ${SRV_PORT}:9292/tcp
    networks:
      - front_net
  post:
    container_name: post
    image: ${USERNAME}/post:${POST_SERVICE_VERSION}
    networks:
      - back_net
      - front_net
  comment:
    container_name: comment
    image: ${USERNAME}/comment:${COMMENT_SERVICE_VERSION}
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  back_net:
    ipam:
      driver: default
      config:
      - subnet: 10.0.2.0/24
  front_net:
    ipam:
      driver: default
      config:
      - subnet: 10.0.1.0/24
