version: '3.3'
services:

  zipkin:
    image: openzipkin/zipkin:2.9.0
    ports:
      - "9411:9411"
    networks:
      - back_net
      - front_net

  fluentd:
    image: ${USER_NAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:5.6
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana:5.6
    ports:
      - "5601:5601"

networks:
  back_net:
  front_net:
